### ISSUE TITLE
Another PD + JUCE implementation

### ISSUE THREAD

**Issue by shakfu** [nicolasdanet/S#2]
Thought you would find this interesting: https://github.com/timothyschoen/PlugData

**Comment by nicolasdanet** [comment]
Thanks for the info.
I already mentioned it in the JUCE forum < https://forum.juce.com/t/has-anyone-tried-porting-pd-to-juce-other-than-cycling-74/39077/5 >.
It is based on libpd and Camomile. The opposite (far more popular) approach to mine. I hope he'll succeed.

**Comment by shakfu** [comment]
Unless these approaches are mutually exclusive, is there any space for collaboration or a unified approach?

**Comment by nicolasdanet** [comment]
No chance since my code is not at all compatible.
I already spent 15000 hours on my project.
I don't have much more time left.

https://github.com/Spaghettis/Spaghettis/discussions/276#discussioncomment-1953195
